### ISSUE TITLE
notifications not working when app is not running

### ISSUE THREAD

**Issue by bathejasumeet** [NativeScript/push-plugin#1]
Notifications do not seem to work when the app is not running (either in foreground or background). 
This includes the scenarios where :
1)App is force stopped
2)Device is restarted

**Comment by AntonDobrev** [comment]
Hello @bathejasumeet,

Can you elaborate a little bit more on the issue you experienced:

* Device platform 
* What is the server implementation for sending push notifications
* What is the payload you are sending 
* Is the notification event called when the app is running (e.g. is in the foreground)

My assumption would be that this concerns Android. We examined a similar issue with a payload that do not include  a **message** key. The plugin for Android is configured to display an entry in the notification tray given the **message** key in the following payload:

```
 {
        "data": {
            "message": "some message",
            "key": "value"
        }
}
```

**Comment by bathejasumeet** [comment]
Hi @AntonDobrev ,

thank you for replying.
     I am using android kitkat. Serverside http://airbop.com/ is being used, payload are normal text messages internally configured using airbop. Tes the notification events are being called while the app is running in the foreground.
    On further investigations, I could find that :
1) Notifications since android 3.1 are not received when app is force stopped : source http://developer.android.com/about/versions/android-3.1.html#launchcontrols
2) In order to receive the notifications when the phone is restarted and app is not started at all, a service along with a broadcast receiver should be used to listen to BOOT_COMPLETED event and register to the server.

I am okay with the first scenario, but am unsure of how to implement the second one in context of NativeScript.
Any help in the matter would be highly appreciated.
Thanks,
bathejasumeet.

**Comment by vbresults** [comment]
Last I checked, in order to do this, you need some sort of background service set up and running to catch the alerts when the app is killed, at least for Android

**Comment by gaurav-chandra** [comment]
This is still a problem. The build fails on android.

**Comment by AntonDobrev** [comment]
@bathejasumeet 

I believe that the issue may be caused by the device cutting off the connection to the Google Cloud Messaging server (due to networking reasons for example). The comment from @vbresults is right on spot, however, this is handled on plugin level and following the [guidelines for implementing a GCM client](https://developers.google.com/cloud-messaging/android/client). 

In such cases you can:

1. Try with a different connection type (3G, 4G, another Wi-Fi network) - the communication between the app and the GCM server is made through a TCP connection. A firewall or a network setting may be blocking the port and the device cannot persist its connection.

2. Check if the port numbers 5228-5230 are allowed in your network

3. Check the connection status to the vendor server by dialing `*#*#426#*#*` on the phone's keyboard.

4. Try to re-establish the connection - shut down the device , send a notification, restart the device.

5. Check if you are receiving notifications on the same device from another app

**Comment by bathejasumeet** [comment]
Hi,  thanks for the reply,  I was working on it yesterday,  don't know how, but your latest build in the month of December seems to have resolved the issue.

**Comment by Daxito** [comment]
I am also having this issue, I dont get any notifications at all after "Force Close" and after "Device Restart", android only, am I missing something here or is it supposed to work?

**Comment by bathejasumeet** [comment]
Which version of android are you running it on, and which phone?

**Comment by Daxito** [comment]
Android 6.0.1, Galaxy5, I was reading that if I "force close" the app then no App would get the notification, but what about a device restart then?

**Comment by Daxito** [comment]
Using in grandle
 ```dependencies {
  compile 'com.google.android.gms:play-services-gcm:+'
}```
and version 0.0.7 of the plugin fixed my issue, after a few seconds, maybe a minute, I start getting notifications.

**Comment by AntonDobrev** [comment]
@Daxito You can upgrade to 0.0.17 (actually I think you meant this versio) which already is using this gradle config.

**Comment by Daxito** [comment]
Thank you @AntonDobrev , yes I meant that version, it is working good now.

**Comment by noetius** [comment]
So, what is the correct approach with plugin version "0.1.2"?

**Comment by mayureshjadhav** [comment]
Started getting the same issue again with v 0.3.0. Can you please help with this?
