### ISSUE TITLE
BUG: Use pure data message, instead of always displaying an notification to the end user

### ISSUE THREAD

**Issue by svzi** [NativeScript/push-plugin#100]
Hi there!

I've already requested this feature some time ago with the old GCM based push-plugin (see https://github.com/NativeScript/push-plugin/pull/51). Sadly the PR is closed and my answer in that thread has been overseen for six days now. So I will re-post my (slightly modified) message here in this post.

In my opinion the current implementation is not working as expected in case of message handling.

May I quote from https://github.com/NativeScript/push-plugin#handling-data-messages:

> **Handling Data Messages**
> When in background mode, a notification is constructed according to the values of the key specified above and placed in the tray. Tapping the notification launches the app and invokes the onMessageReceived callback.

FCM, as well as GCM, knows two types of messages to clients (compare https://firebase.google.com/docs/cloud-messaging/concept-options#notifications_and_data_messages):

> * Notification messages, sometimes thought of as "display messages."
> * Data messages, which are handled by the client app.

Only Notification messages are meant to be displayed to the end-user. How they should be displayed is configured by the notification key! Data messages don't have a notification key, that means they are not meant to be displayed to the user. They're meant to enable some kind of data processing of the client app.

But when I send this (data) message to my device:
`{
    to: 'my-device-key',
    data: {
        your_custom_data_key: 'your_custom_data_value'
    }`

It shows again up as empty notification in the notification tray. No title, no body. That's not the way it should work. This message should not be displayed in the notification tray according to the FCM documentation!

Additionally your README also states that:

> The onMessageReceived method of the plugin is called each time a data notification is received.

That's not the way it works here on my devices. That method is only called when I tap on the (empty) notification, placed in the notification tray. Maybe it would work as described, if the data message wouldn't be shown in the notification tray.

**Comment by AntonDobrev** [comment]
@svzi 

You are bringing up some valid points here which I will address below. I also apologize for missing the comment in the PR but it's good that you raised it here to make this more visible. 

Yes, you are correct that `data` and `notification` keys differ in their usage. With adding the native Firebase SDK to the plugin we obtained the logical and native separation of the purposes of the both keys. However, before a `notification key was added and automatically handled by the Firebase SDK, the `data` key was the one used to construct the notification` in the tray. 

Another specific is that it is hard to incorporate the logic of handling the received data message in a place different than the native Java code of the plugin. 

This said, my suggestion here for a feature request is to add a separate flag in the way the `data` arguments are handled and allow for the developer to control from the server if the message should be shown in the tray or just be handled as data sent to the app, leaving the `notification `payload to construct the user notification.  

Another enhancement is to display nothing if there is no `title` and `message` in the data payload. 

Also, this is reliying on the presence of a notification so that the arguments are available when the user taps on the notification in the tray. 

My concerns are also in terms of compatibility, because a lot of developers are not using the `notification` key in their old apps and updating them with the new plugin will introduce a breaking change in their client apps and their servers. 

Can you please elaborate on the above, what do you think?

Also, thanks for the remark on the documentation. This line sort of confuses the behavior of the native onMessageReceived callback and the plugin callback, Your observations are correct, it should better state "...each time when the app is in the foreground and the notification is received, and when a user taps on the notification in the tray... "

I look forward to your reply. 

Best,
Anton

**Comment by svzi** [comment]
@AntonDobrev 

> Yes, you are correct that data and notification keys differ in their usage. With adding the native Firebase SDK to the plugin we obtained the logical and native separation of the purposes of the both keys. However, before a notification key was added and automatically handled by the Firebase SDK, the data key was the one used to construct the notification in the tray.

I'm sorry, but I think you're wrong with that. GCM handled push messages exactly the same way as Firebase does it now. GCM had exactly the same concepts. Compare here: https://developers.google.com/cloud-messaging/concept-options#payload

I already reported a bug in October 2016: https://github.com/NativeScript/push-plugin/issues/50 
That issue was the reason I've created the PR: https://github.com/NativeScript/push-plugin/pull/51 

> This said, my suggestion here for a feature request is to add a separate flag in the way the data arguments are handled and allow for the developer to control from the server if the message should be shown in the tray or just be handled as data sent to the app, leaving the notification payload to construct the user notification.

I don't like that idea, because, in my opinion, push messages, no matter if send via GCM or Firebase, should be handled the way they should be, according to the official documentation(s). No matter if someone is using NativeScript or another Framework. I expect the messages to behave the same way. There is already a flag, it's called `notification`. If that property is set, a message should be shown to the end user. When the property is missing, the message is not meant to be shown to the user (Google said that and Firebase says it as well).

> My concerns are also in terms of compatibility, because a lot of developers are not using the notification key in their old apps and updating them with the new plugin will introduce a breaking change in their client apps and their servers.

I'm really not sure about that. You could be right with your assumption, but I don't know about. If you're right about that, it would also mean that they all use the push messages in a kind that was not supposed to work (from Google and Firebase). They probably could only use it this way, because of this bug. I would also like to change this from *Feature Request* / *Enhancement* to *Bug*, because in my opinion it's a bug and it was even there before the switch to Firebase.

Thanks for your support! 👍 

Best,
Sven

**Comment by AntonDobrev** [comment]
@svzi Thanks for your detailed and honest feedback, Sven. I will propose this for consideration to the other contributors, your points are pretty sound and (at least) worth checking. I do also agree with your position and understand your point. 

At the moment I cannot provide more information or commit to some action, though, but stay tuned. Any further thoughts, ideas are welcome.

**Comment by svzi** [comment]
@AntonDobrev Any feedback on this issue?

I would also like to ask you to remove the **enhancement** label and to replace it with **bug**.

**Comment by idoadse** [comment]
Is there anything new with this issue?

**Comment by DimitarTachev** [comment]
Hi guys,

Sorry for the long silence.

In order to receive a pure data message, you just need to send such one from FCM using the request below:

>curl -X POST --header "Authorization: key=SERVER_KEY" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"DEVICE_TOKEN\"}"
