### ISSUE TITLE
What is the minimum android sdk version supported ?

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/push-plugin#102]
I'm receiving an error on API 17: `JS: Error on push notification registration: Error while retrieving a token: PHONE_REGISTRATION_ERROR`

But I do not know if related to the version ?, because it works fine on newer versions.

**Comment by AntonDobrev** [comment]
@ignaciolarranaga 

I think it is safe to use with API level 17 (since this is also supported in {N}). However, this only applies to being able to compile and manage copatibilities at runtime. 

In the present case I think there is a problem with the Google Play services app on the device and it may be good to update it, refresh it, clear all data, or somehow sanitize the Google Play on the app since it should be responsible for managing the device registration. 

Can you please try this on your side?
