### ISSUE TITLE
onMessageReceived callback is now executed even if app is running in background

### ISSUE THREAD

**Issue by ickata** [NativeScript/push-plugin#162]
`onMessageReceived` callback is executed immediately after notification is received on Android, using plugin version 0.2.0. With plugin version 0.1.5 the callback was executed when I click on the notification from the tray (just like it is on iOS). What changed?

**Comment by lini** [comment]
In version 0.2.0 we removed code from the native library for Android, that was used for creating the notification icon in the system tray, because it was not compatible with Oreo and now the Android OS is responsible for handling and displaying the notification when the app is suspended/closed. Perhaps this caused the changed behavior of the message callback function?

We've also added a demo app in the plugin repository so you can try testing there as well and compare the behavior with your app.  The app.ts file in the demo has a function that is used to handle data from notifications received while the app is not in the foreground - https://github.com/NativeScript/push-plugin/blob/master/demo/app/app.ts

**Comment by ickata** [comment]
Hi @lini ,

Thank you for the response. So, you are telling that there won't be backward-compatibility and `onMessageReceived` callback won't be executed when app is resumed from background? Then probably you should point out this as a "Breaking change" in the [0.2.0 release](../releases/tag/v0.2.0). 

I also cannot get notification icon in the tray as well as sound. Here is what my notification payload contains (this is what I send to FCM from my server):

```
   {
      to    : "device_token",
      data  : {
         "custom_key": "value",
      },
      notification : {
         title       : "title",
         body     : "message",
         smallIcon   : 'icon_notify',  // defined in App_Resources
         sound       : 'notify',       // defined in App_Resources
      },
   }
```

This used to work in version 0.1.5 . Also in this version the notification payload looked different. I did not have the "notification" key, everything was inside the "data":

```
   {
      to    : "device_token",
      data  : {
         "custom_key": "value",
         title       : "title",
         message     : "message",
         smallIcon   : 'icon_notify',  // defined in App_Resources
         sound       : 'notify',       // defined in App_Resources
      },
   }
```

This used to work. Any advice?

**Comment by ickata** [comment]
I'll create new issue and will close this one. The `onMessageReceived` callback was executed even when in background as the payload was handled as a data message, not "mixed" notification + data message.

**Comment by cerireyhan** [comment]
@ickata Is this issue fixed or do you know a way of handling data messages on android?

**Comment by ickata** [comment]
Hi,

Issue is not fixed. To be able to handle data messages you have to ensure that you send them as "data" messages, nor "notification" neither "mixed". onMessageReceived callback is always called for data messages. More info here: https://firebase.google.com/docs/cloud-messaging/concept-options

Hope this helps.

**Comment by cerireyhan** [comment]
Hi @ickata 
I'm getting only data messages on iOS and process/put it in the notification center manually by overriding applicationDidReceiveRemoteNotification in app delegate. However, it doesn't seem possible in the current situation of Android. Thanks for the help. Open to any suggestions. :)
