### ISSUE TITLE
[Android] Missing notification tray icon

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/push-plugin#185]
So seems that you have "silently" removed `NotificationBuilder` class: https://github.com/NativeScript/push-plugin/blob/0.1.2/native-src/android/app/src/main/java/com/telerik/pushplugin/NotificationBuilder.java

And related code to create a notification in the tray icon area with the respective icon: 
https://github.com/NativeScript/push-plugin/blob/0.1.2/native-src/android/app/src/main/java/com/telerik/pushplugin/PushPlugin.java#L133-L135
https://github.com/NativeScript/push-plugin/blob/0.1.2/native-src/android/app/src/main/java/com/telerik/pushplugin/NotificationBuilder.java#L75

Again absolutely no mention for this in the change log of breaking changes and how should users migrate their existing apps. So how should we migrate our code to v0.3 of this plugin? Are we supposed to include the whole `NotificationBuilder.createNotification()` method code in every app that wants to have proper icons in the tray???

**Comment by lini** [comment]
Hi,
The NotificationBuilder class was removed to make the plugin compatible with Android Oreo. Now, the FCM SDK is responsible for creating the notification area icons and the way it does this has not changed. At the very bottom of the plugin documentation you can see how to set the default notification icon for the app from the AndroidManifest.xml file:
```XML
<meta-data
        android:name="com.google.firebase.messaging.default_notification_icon"
        android:resource="@drawable/ic_stat_ic_notification" />
```

where `ic_stat_ic_notification` is the name of the image file resource in the app.

If you want to use a custom notification icon for a specific message instead of the default one, you can set it from the JSON payload of the notification:
```JSON
{
  "notification": {
    "title": "My title", 
    "text": "My text", 
    "sound": "default",
    "icon": "myicon" 
  },
  "to":"DEVICE_FCM_TOKEN"
}
```
where `myicon` is the name of the image file resource in the app.

**Comment by PeterStaev** [comment]
Thanks @lini ! Missed the explanation in the README... 

For future please make sure you include such breaking changes in the change log so users know how to migrate between plugin versions 😃
