### ISSUE TITLE
App does not start after adding push plugin

### ISSUE THREAD

**Issue by bathejasumeet** [NativeScript/push-plugin#20]
I added push plugin to nativescript project , after I execute

tns run android 

the nativescript cli says " successfully  launched on device", but the app does not launch on device, there is no feedback, neither error on the device, nor on the nativescript cli.

when I remove the plugin, the app launches fine on device.
Testing it on android 4.4 device.

**Comment by frierdich** [comment]
Might have a solution for this.  I was having the same issue after adding the plugin.

I copied all of the relevant pieces of the AndroidManifest.xml that were specific to the plugin and placed them into the "generic" app/App_Resources/Android/AndroidManifest.xml.  Now the app will start on my emulator.

Note, you may need to clear out the "F*" directories in /platforms/android/build/intermediates/classes/ although this may not be required.

Note, I haven't actually tested the functionality of the "push" plugin yet, but at least my app is now able to start with the plugin installed.

Hopefully the devs responsible for this project will update the "push" plugin to be compatible with the 2.0 version of NS.

**Comment by AntonDobrev** [comment]
@bathejasumeet @frierdich 

The issue is not reproducible with this sample app [sample-push-plugin](https://github.com/NativeScript/sample-push-plugin).

1. Clone the repo
2. Configure the code 
3. Make sure you have the latest NS runtime 2.0 and the NS modules 2.0 installed
4. Run `tns remove android` 
5. Run `tns add android`
5. Run `tns run android` as you'd normally do

The app installs and runs successfully. 

The plugin should be considered for upgrade to 2.0 compatibility though, perhaps its structure may introduce problems with other plugins/modules for NS after 2.0.
