### ISSUE TITLE
enabledRemoteNotificationTypes is not supported in iOS 8.0 and later.

### ISSUE THREAD

**Issue by myso-kr** [NativeScript/push-plugin#24]
https://github.com/phonegap/phonegap-plugin-push/commit/855f1abae8f3edca51a459f546db169515149128

**Comment by spstratis** [comment]
@myso-kr Are you having this problem with Nativescript or Phonegap? I noticed you tagged a phone gap commit.

**Comment by AntonDobrev** [comment]
@myso-kr @spstratis 

Thanks.

The plugin utilizes this API for runtime lower than iOS 8 to check for _areNotificationsEnabled_. Technically speaking, if you are testing against at least iOS 8 you should not get any issues with the unsupported _enabledRemoteNotificationTypes_ because the plugin will use the new API from UIApplication - _isRegisteredForRemoteNotifications_. Otherwise the check will fallback to _enabledRemoteNotificationTypes_.
