### ISSUE TITLE
is there click_action to open certain page from notification

### ISSUE THREAD

**Issue by ilyago** [NativeScript/push-plugin#37]
If app is open, I don't get notification but JSON data is received in app.
If app is closed, I receive notification but JSON data is not received in app.

GCM has click_action. How can I call certain action when notification is tapped, right now it opens main home page only.

**Comment by AntonDobrev** [comment]
@ilyago 

This is discussed in #6 - please share any comments there. I will close this one now.

**Comment by AntonDobrev** [comment]
@ilyago 

Can you elaborate more on _If app is closed, I receive notification but JSON data is not received in app._ Is this happening when you tap on the notification. Also, what is the logic executed on the launch of the app in the success callback - is it UI-related? You should be able to receive the notification arguments, but due to a certain limitation, any UI component interaction may crash. 

If this is the issue an idea how to fix this can be found in this PR - https://github.com/NativeScript/sample-push-plugin/pull/6/commits/22f204f05e5b596d60f86ad243ea9756b697fbcd
