### ISSUE TITLE
ios device is getting unregistered from Telerik Platform

### ISSUE THREAD

**Issue by Daxito** [NativeScript/push-plugin#79]
ios device is getting unregistered from Telerik Platform. 
It registers the first time but then when I send a notification the devices is automatically unregistered in the backend, as if I called "unregister" from the App itself.
But even if I turn off the device and send the notification the device is removed. 
Any ideas?
Using:
Xcode 8.2.1 
NS 2.4.2.

**Comment by AntonDobrev** [comment]
@Daxito 

Can you please specify - is the device becoming inactive (e.g. Active: false) in the backend or the registration is removed? The latter sounds peculiar and actually there is no logic that may do this, either on the server or in the client frameworks. 

If the former - please check [here](http://docs.telerik.com/platform/backend-services/javascript/push-notifications/troubleshooting/push-trb-ios.html). 

Can you please share any more details you may have?

**Comment by Daxito** [comment]
The issue is the former, I see the device in Telerik backend but it sets as Active=false when sending the first notification (and no notifications are actually sent at all).
I used to have XCode 7.3.1 (or 7.3.2) and I installed XCode 8.2.1 so I suspect something to do with this new XCode version. 

The issue is just when debugging, I can confirm the after releasing the App to the App Store, the notifications work, so seems like an issue with the developer certificates or something, I will take a look at the provided documentation.

**Comment by Daxito** [comment]
Device is not set as inactive anymore after resetting the Push Notifications Certificate in my Mac and re-uploaded it to Telerik Platform, so that is fixed.
 
But, notifications are received when I run the app from XCode and set the capability to support Push Notifications but when I run it using "tns run ios" notifications are not received, (again, the device is NOT set as Inactive anymore, it is active in the backend, but I just don't get any notifications)

I am not sure if this would be an issue with {N} or with this plugin ... ?

Thanks!

**Comment by AntonDobrev** [comment]
@Daxito I believe that what you experienced is explained in the comments below and mostly are by design.

1. When the device is inactive in Telerik Platform it does not fall under any target audience, until it becomes active again. This is a behavior in Telerik Platform. 
2. When you deploy the app again on the device, especially on iOS 10, a new push token for development is generated. This said, the device cannot be reached by the old tokens and usually they become invalid and the device registration with such token inactive. You need to register the device again after deploying the app on it. This is a behavior of iOS. 
3. You cannot obtain a push token on the device with success if the Push Notifications capability is not added from your IDE (in this case - Xcode). That is why you need to prepare the app and open it in Xcode to add the capability, then deploy. This comes from Xcode 8. 

I hope this helps.
